baseURL = 'https://shaoqisama.github.io/'
languageCode = 'en-us'
title = 'shaoqisama'
theme = 'hugo-PaperMod'

resourceDir = "../resources"

DefaultContentLanguage = "en"
# SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe = true

[pagination]
pagerSize = 10 # this is set low for demonstrating with dummy content. Set to a higher number

[languages]
[languages.en]
# weight = 1
# contentDir = "content/"
# languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = "shaoqisama"
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
homeLayout = "home_info"
ShowReadingTime = true
ShowShareButtons = true
comments = true
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose an fitting and alignment style for the featured image using tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or size header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 3
mainSections = ["posts", "music"]

[params.homeInfoParams]
Title = "Hi there!"

Content = "Welcome to the official Shaoqisama website! 🎨✨ I'm a musician🎵, photographer 📸, and coder 💻. Let's build beautiful things together! 🚀🌟"

[[params.socialIcons]]
name = "applemusic"
url = "https://music.apple.com/cn/artist/shaoqisama/1771827138"

[[params.socialIcons]]
name = "github"
url = "https://github.com/shaoqisama"

[[params.socialIcons]]
name = "email"
url = "mailto:acousticsung@gmail.com"


[params.ananke.social.follow]
new_window_icon = false # show a little "opens in new window" icon next to the link
networks = [
  "facebook",
  "bluesky",
  "linkedin"
]

[params.ananke.social]
[params.ananke.social.facebook]
username = "patrick.kollitsch"
# profilelink = "https://www.facebook.com/patrick.kollitsch"

[params.ananke.social.linkedin]
username = "patrickkollitsch"

[params.ananke.social.bluesky]
username = "kollitsch.dev"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Music'
    pageRef = '/music'
    weight = 20
  [[menus.main]]
    name = 'Gallery'
    pageRef = '/gallery'
    weight = 30
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 40

[services]
  [services.disqus]
    shortname = 'shaoqisamablog'
    
[module]
[[module.imports]]
path = "github.com/rootwork/hugo-module-gallery-grid"